version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - type/chore
      - area/ci
  - package-ecosystem: pip
    directory: /scripts
    schedule:
      interval: monthly
    labels:
      - type/chore
      - area/ci
